# Generated by Django 4.0.4 on 2024-02-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_rename_user_employee_refrence_id_employee_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
