# Generated by Django 4.0.4 on 2024-02-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_employee_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='grade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
