# Generated by Django 4.0.4 on 2024-02-29 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0004_alter_employee_grade_alter_employee_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='refrence_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
