# Generated by Django 4.0.4 on 2024-03-01 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_employee_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('Registered', 'Registered'), ('Headquarters', 'Headquarters'), ('Branch', 'Branch')], max_length=50)),
                ('primary_address', models.BooleanField(default=False)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=20)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='crm.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRegistrationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.CharField(choices=[('Type A', 'Type A'), ('Type B', 'Type B'), ('Type C', 'Type C')], max_length=50)),
                ('registration_since', models.DateField(blank=True, null=True)),
                ('registration_number', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_details', to='crm.company')),
            ],
        ),
        migrations.CreateModel(
            name='LocationRegistrationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('Registered', 'Registered'), ('Headquarters', 'Headquarters'), ('Branch', 'Branch')], max_length=50)),
                ('registration_type', models.CharField(choices=[('Type X', 'Type X'), ('Type Y', 'Type Y'), ('Type Z', 'Type Z')], max_length=50)),
                ('registration_since', models.DateField(blank=True, null=True)),
                ('registration_number', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_registration_details', to='crm.company')),
            ],
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
