# Generated by Django 4.0.4 on 2024-03-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_admincompany_alter_companyaddress_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_company_admin',
            field=models.BooleanField(default=False),
        ),
    ]
