# Generated by Django 4.0.4 on 2024-03-04 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_admincomp_location_delete_companyaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Comp_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('Registered', 'Registered'), ('Headquarters', 'Headquarters'), ('Branch', 'Branch')], max_length=50)),
                ('primary_address', models.BooleanField(default=False)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=20)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_comp_Location_RegistrationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(max_length=100)),
                ('registration_type', models.CharField(max_length=100)),
                ('registration_since', models.DateField(blank=True, null=True)),
                ('registration_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Comp_RegistrationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.CharField(max_length=100)),
                ('registration_since', models.DateField(blank=True, null=True)),
                ('registration_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='contact_company_logos/')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('group', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('sales_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('num_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('industry_type', models.CharField(blank=True, max_length=100)),
                ('industry_sub_type', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_companies', to='crm.employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='locationregistrationdetails',
            name='company',
        ),
        migrations.DeleteModel(
            name='CompanyRegistrationDetails',
        ),
        migrations.DeleteModel(
            name='LocationRegistrationDetails',
        ),
        migrations.AddField(
            model_name='contact_comp_registrationdetails',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_details', to='crm.contactcompany'),
        ),
        migrations.AddField(
            model_name='contact_comp_location_registrationdetails',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_registration_details', to='crm.contactcompany'),
        ),
        migrations.AddField(
            model_name='contact_comp_address',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='crm.contactcompany'),
        ),
    ]
