# Generated by Django 4.0.4 on 2024-03-05 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_contact_comp_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='contact_photos/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('facebook', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('whatsapp', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('other_social_link', models.URLField(blank=True)),
                ('associated_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='crm.contactcompany')),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='SignificantDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_type', models.CharField(choices=[('Birthday', 'Birthday'), ('Anniversary', 'Anniversary'), ('Other', 'Other')], max_length=50)),
                ('date', models.DateField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='significant_dates', to='crm.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('Family', 'Family'), ('Friend', 'Friend'), ('Colleague', 'Colleague'), ('Other', 'Other')], max_length=50)),
                ('relationship_name', models.CharField(max_length=100)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='crm.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_type', models.CharField(choices=[('Personal', 'Personal'), ('Work', 'Work'), ('Other', 'Other')], max_length=50)),
                ('primary_mobile', models.BooleanField(default=False)),
                ('mobile', models.CharField(max_length=15)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiles', to='crm.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Landline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landline_type', models.CharField(choices=[('Personal', 'Personal'), ('Work', 'Work'), ('Other', 'Other')], max_length=50)),
                ('primary_landline', models.BooleanField(default=False)),
                ('landline', models.CharField(max_length=15)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlines', to='crm.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('Personal', 'Personal'), ('Work', 'Work'), ('Other', 'Other')], max_length=50)),
                ('primary_email', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='crm.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('Other', 'Other')], max_length=50)),
                ('primary_address', models.BooleanField(default=False)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=20)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='crm.contact')),
            ],
        ),
    ]
