# Generated by Django 4.0.4 on 2024-03-06 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0014_contact_significantdate_relationship_mobile_landline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_date', models.DateField()),
                ('lead_status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Converted', 'Converted'), ('Closed', 'Closed')], max_length=50)),
                ('requirement', models.TextField()),
                ('requirement_attachment', models.FileField(blank=True, null=True, upload_to='requirement_attachments/')),
                ('lead_source', models.CharField(choices=[('Website', 'Website'), ('Referral', 'Referral'), ('Advertisement', 'Advertisement'), ('Cold Call', 'Cold Call'), ('Other', 'Other')], max_length=100)),
                ('contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contact')),
                ('lead_assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('primary_lead_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_type', models.CharField(choices=[('Call', 'Call'), ('Meeting', 'Meeting'), ('Email', 'Email'), ('Other', 'Other')], max_length=50)),
                ('follow_up_date_and_time', models.DateTimeField()),
                ('follow_up_notes', models.TextField()),
                ('follow_up_attachment', models.FileField(blank=True, null=True, upload_to='follow_up_attachments/')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='crm.leads')),
            ],
        ),
    ]
