# Generated by Django 4.0.4 on 2024-03-06 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_leads_followup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='lead_assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_assigned_to', to='crm.employee'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='primary_lead_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_created', to='crm.employee'),
        ),
    ]
